# Generated by Django 4.0.3 on 2022-04-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurProfile', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
